- hosts: k8smaster
  become: yes
  user: ubuntu
  roles: 
  - { role: install-helm, tags: ["install_helm3_role"] }

- hosts: k8smaster
  become: yes
  user: ubuntu
  roles: 
  - { role: install-monit-tools, tags: ["install_monit_tools_role"] }