---
- name: Instalando dependências da instalação
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates

- name: Adicionando a chave do repo oficial do Docker para o containerd
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg    

- name: Adicionando o repo do containerd
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    filename: containerd.list    

- name: Instalando o containerd
  apt: 
    name: containerd

- name: Criando  pasta de configuração do containerd
  file:
    path: /etc/containerd
    state: directory

- name: Criando arquivo de config default do containerd
  shell: "containerd config default | sudo tee /etc/containerd/config.toml"  

- name: "Configurar Systemd como cgroup driver do containerd"  
  replace:
    path: /etc/containerd/config.toml
    regexp: "SystemdCgroup = false"
    replace: "SystemdCgroup = true"
  
- name: Restart containerd
  service:
    name: containerd
    state: restarted
