- name: Instalando dependências da instalação
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates    
    - curl
    - gnupg

- name: Adicionando a chave do repo oficial do Docker para o containerd
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg    

- name: Adicionando o repo do containerd
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    filename: containerd.list    

- name: Instalando o containerd
  apt: 
    name: "{{ packages }}"    
  vars:
    packages:
    - apt-transport-https
    - ca-certificates    
    - containerd

- name: Chave  do repo oficial do K8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Adicionando o repo do K8s
  apt_repository: 
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Instalando os pacotes kubeadm, kubelet e kubectl
  apt: 
    name: "{{ packages }}"    
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  