- name: Carregar os módulos do kernel para K8s e Containerd
  copy:
    src: templates/kernel-modules-k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Configurar o ip tables para receber os pacotes do netfilter
  copy:
    src: templates/netfilter-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Habilitar o ip forwarding com sysctl
  lineinfile:
    path: /etc/sysctl.conf
    insertafter: "#net.ipv4.ip_forward=1"
    line: "net.ipv4.ip_forward=1"

- name: Aplicar configurações com sysctl imediatamente
  shell: sysctl -p

- name: Desabilitar Swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Habilitando Cgroups necessários
  replace:
    path: /boot/firmware/cmdline.txt    
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  notify: restart

# - name: Liberando portas no firewall (ufw) para o Kubernetes
#   community.general.ufw:
#     rule: allow
#     interface: eth0
#     direction: in
#     proto: udp
#     src: 1.2.3.5
#     from_port: '5469'
#     dest: 1.2.3.4
#     to_port: '5469'
